# Generated by Django 3.1.3 on 2020-11-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='documentNumber',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='documentType',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
