# Generated by Django 3.1.3 on 2020-11-13 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201113_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
